SELECT 
	TABLE_CONSTRAINTS.TABLE_NAME AS '$table',
	KEY_COLUMN_USAGE.COLUMN_NAME AS '$column',
	TABLE_CONSTRAINTS.CONSTRAINT_TYPE AS '$constraintType',
    TABLE_CONSTRAINTS.CONSTRAINT_NAME AS '$constraintName',
	KEY_COLUMN_USAGE.REFERENCED_TABLE_NAME AS '$referencedTable',
    KEY_COLUMN_USAGE.REFERENCED_COLUMN_NAME AS '$referencedColumn',
    KEY_COLUMN_USAGE.ORDINAL_POSITION AS '$ordinalPosition',
    KEY_COLUMN_USAGE.POSITION_IN_UNIQUE_CONSTRAINT AS '$positionInUniqueConstraint'
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
	LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    ON KEY_COLUMN_USAGE.TABLE_SCHEMA = TABLE_CONSTRAINTS.TABLE_SCHEMA
      AND KEY_COLUMN_USAGE.TABLE_NAME = TABLE_CONSTRAINTS.TABLE_NAME
      AND KEY_COLUMN_USAGE.CONSTRAINT_NAME = TABLE_CONSTRAINTS.CONSTRAINT_NAME
	WHERE TABLE_CONSTRAINTS.TABLE_SCHEMA = '${DATABASE_NAME}'
		AND TABLE_CONSTRAINTS.CONSTRAINT_TYPE != 'PRIMARY KEY';